### ISSUE TITLE
reset option for talk is missing

### ISSUE THREAD

**Issue by pandorabots** [pandorabots/pb-cli#1]
Pandorabots API talk API has a reset parameter used for bot development that clears out a bots memory if set to true. This is missing in the CLI and should be included as an option.

**Comment by pbyk** [comment]
Thank you for your report! That's bug of handling --option style parameter.
At this moment,
$ pb --reset=true talk 'my name?'
doesn't work, however,
$ reset=true pb talk 'my name?'
works properly (that means bot forgets my name).
I'll fix this bug soon.

**Comment by pbyk** [comment]
I fixed the bug.
