### ISSUE TITLE
Poor error reporting

### ISSUE THREAD

**Issue by cfjedimaster** [pandorabots/pb-cli#11]
I created a bot using the Playground and downloaded the zip. I unzipped it and then tried to push it using the CLI. This is what I got:

![image](https://cloud.githubusercontent.com/assets/393660/15945511/7d9db318-2e58-11e6-97de-9ef689381d7e.png)

I've got no idea what to do. That's 8 errors - but they are so vague I can't tell what it means. Not only that, if they apply to particular files in my bot, I can't tell because no files are reported with the errors.

**Comment by cfjedimaster** [comment]
I think I figured it out. I had not run `pb create voltron` yet. Totally my fault, but the CLI could have made that clear. I've got voltron defined in chatbot.json so it should have recognized I was pushing to a bot not yet created.

**Comment by cfjedimaster** [comment]
Just checking - is this project still alive?

**Comment by pandorabots-admin** [comment]
Release 1.1.1 updated to support improved error messages.
