### ISSUE TITLE
Support subdirectories of files

### ISSUE THREAD

**Issue by cfjedimaster** [pandorabots/pb-cli#12]
When you download rosie, you get a bunch of files in various subdirectories (aiml, maps, sets, etc). But you can't pb push from the root directory as no files exist. So I have to push each subdirectory by hand. Maybe pb push can scan subdirectories if a flag is provided?

**Comment by keeth** [comment]
I have exactly the same question, it's not clear how to push a whole project like rosie. Help?

**Comment by pandorabots-admin** [comment]
Release 1.1.1 updated to support in pb push.
