### ISSUE TITLE
Downloading .zip file with incorrect credentials is broken

### ISSUE THREAD

**Issue by djfdev** [pandorabots/pb-cli#9]
To recreate:
1. Create a chatbot.json file with a bad user_key.
2. Download .zip of bot files:

```
$ pb get --all
```

The CLI creates <yourbot>.zip file, but it cannot be unzipped. This command should display an "unauthorized" error in the case that bad credentials are supplied.

**Comment by pbyk** [comment]
Thank you for your bug report!
Next major release will solve HTTP 401 error with showing message below.

```
error: authorization problem. check app_id and/or user_key
```
